version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/revobank.db
      - JWT_SECRET_KEY=your-secret-key-here
    command: flask run --host=0.0.0.0

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: revobank
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: